name: Code coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov pytest codecov

    - name: Run tests
      run: |
        pytest --cov=src --cov-branch --cov-report=xml backend/test/

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
